[pytest]
testpaths = tests
pythonpath = .
addopts = --import-mode=importlib
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated.*:starlette.exceptions.StarletteDeprecationWarning
